/** ServisPilot — Tailwind derleme yapılandırması
 *  cdn.tailwindcss.com üretim için kaldırıldı; bu config index.html'deki
 *  eski inline config'in birebir kopyasıdır.
 *  Derleme:  npx tailwindcss@3.4.17 -i css/input.css -o css/tailwind.min.css --minify
 */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./giris.html",
    "./gizlilik.html",
    "./kullanim-sartlari.html",
    "./js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "paper": "#F4F6F9",
        "card": "#FFFFFF",
        "navy": "#0E1B2C",
        "navy-2": "#13223A",
        "ink": "#16202E",
        "ink-soft": "#3D4A5A",
        "muted": "#5B6B7C",
        "line": "#E1E7EE",
        "accent": "#E8930C",
        "accent-soft": "#FFC174",
        "accent-deep": "#B45309",
        "green-ok": "#1B8A4B",
        "surface-base": "#F4F6F9",
        "surface": "#F4F6F9",
        "surface-card": "#FFFFFF",
        "surface-card-elevated": "#FFFFFF",
        "surface-container-lowest": "#F7F9FC",
        "surface-container-low": "#EEF1F5",
        "surface-container": "#E7EBF1",
        "surface-container-high": "#DFE5EC",
        "surface-container-highest": "#D3DBE4",
        "surface-bright": "#FFFFFF",
        "background": "#F4F6F9",
        "surface-dim": "#EDE8DD",
        "surface-variant": "#F7F9FC",
        "text-primary": "#16202E",
        "on-surface": "#1C2733",
        "on-surface-variant": "#64748B",
        "text-secondary": "#5B6B7C",
        "text-muted": "#64748B",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-error-container": "#410E0B",
        "secondary-fixed": "#ffdbce",
        "secondary-container": "#f66018",
        "tertiary-container": "#e0a800",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#ffffff",
        "secondary-fixed-dim": "#ffb599",
        "tertiary-fixed": "#ffdf9f",
        "inverse-primary": "#855300",
        "primary": "#E8930C",
        "primary-container": "#f59e0b",
        "primary-fixed": "#FFC174",
        "primary-fixed-dim": "#f59e0b",
        "on-primary": "#472A00",
        "on-primary-container": "#472A00",
        "on-primary-fixed": "#472A00",
        "on-primary-fixed-variant": "#472A00",
        "error": "#B3261E",
        "on-error": "#FFFFFF",
        "error-container": "#F9DEDC",
        "outline": "#9AA4AF",
        "outline-variant": "#C9C2B2",
        "border-subtle": "rgba(22, 32, 46, 0.08)",
        "glow-amber": "rgba(232, 147, 12, 0.12)",
        "tertiary": "#ffc32d",
        "tertiary-fixed-dim": "#f9bd22",
        "on-tertiary": "#402d00",
        "on-tertiary-container": "#584000",
        "on-tertiary-fixed": "#261a00",
        "inverse-surface": "#16202E",
        "inverse-on-surface": "#F4F6F9",
        "on-secondary-fixed": "#ffffff",
        "on-secondary-fixed-variant": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-2xl": "4rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-3xl": "6rem",
        "margin": "3rem"
      },
      fontFamily: {
        "label-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "code-metric": ["Space Grotesk", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"],
        "display-mobile": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-md": ["0.875rem", { "lineHeight": "1.25rem", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-sm": ["1.25rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "code-metric": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "500" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-lg": ["2.5rem", { "lineHeight": "3rem", "letterSpacing": "-0.025em", "fontWeight": "700" }],
        "label-sm": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.375rem", "fontWeight": "400" }],
        "body-md": ["1rem", { "lineHeight": "1.5rem", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "display": ["3.75rem", { "lineHeight": "4.25rem", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "display-mobile": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.025em", "fontWeight": "800" }],
        "headline-lg-mobile": ["1.875rem", { "lineHeight": "2.375rem", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.02em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")]
};
